name: pravinkumard/ASP.NET_8
on:
  push:
    branches:
    - main
jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Install .NET SDK 8.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.x
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Restore NuGet Packages
      run: dotnet restoreaspdotnetproj.csproj

    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Build Solution
      run: dotnet build aspdotnetproj.csproj --configuration Release
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Run Tests
      run: dotnet testaspdotnetproj.csproj --logger trx --results-directory "${{ runner.temp }}" --configuration Release
    - name: Run Tests
      uses: NasAmin/trx-parser@v0.5.0
      if: always()
      with:
        TRX_PATH: "${{ runner.temp }}"
        REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Publish
      run: dotnet publish aspdotnetproj.csproj --configuration Release --output ${{ runner.temp }}/publish
    - name: Publish Artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop
        path: "${{ runner.temp }}/publish"
